#ifndef SLINT_BINDINGS_H
#define SLINT_BINDINGS_H

/* Generated by cbindgen from crates/slint-bindings-ffi. Do not edit; run `just header`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Mouse buttons, mirrored by the Swift and C# wrappers.
 */
enum SbPointerButton
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * Primary button.
   */
  SB_POINTER_BUTTON_LEFT = 0,
  /**
   * Secondary button.
   */
  SB_POINTER_BUTTON_RIGHT = 1,
  /**
   * Wheel button.
   */
  SB_POINTER_BUTTON_MIDDLE = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum SbPointerButton SbPointerButton;
#else
typedef uint8_t SbPointerButton;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Opaque handle to the demo form and its pixel buffer.
 */
typedef struct SbHost SbHost;

/**
 * Result of [`sb_host_render`].
 */
typedef struct SbFrame {
  /**
   * 1 when the buffer was written, 0 when the previous frame is still valid.
   */
  uint8_t redrawn;
  /**
   * 1 while animations run: render again on the next vsync.
   */
  uint8_t animating;
  /**
   * 1 when the call failed; see `sb_last_error`.
   */
  uint8_t failed;
} SbFrame;

/**
 * C callback for `submitted(string)`: `user_data`, then the UTF-8 name. Null clears it.
 */
typedef void (*SbSubmittedFn)(void *user_data, const char *name);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Message of the last failed call on this thread, or null. Valid until the next `sb_*` call.
 */
const char *sb_last_error(void);

/**
 * Creates the demo form at `width`×`height` physical pixels. Null on failure.
 */
struct SbHost *sb_demo_new(uint32_t width, uint32_t height, float scale);

/**
 * Destroys a host. Null is ignored.
 *
 * # Safety
 * `host` must be null or a pointer from [`sb_demo_new`] not freed before.
 */
void sb_host_free(struct SbHost *host);

/**
 * Bytes the buffer passed to [`sb_host_render`] must hold; 0 for a null host.
 *
 * # Safety
 * `host` must be null or live.
 */
size_t sb_host_frame_len(const struct SbHost *host);

/**
 * Resizes the frame; returns false on failure.
 *
 * # Safety
 * `host` must be null or live.
 */
bool sb_host_resize(struct SbHost *host, uint32_t width, uint32_t height, float scale);

/**
 * Renders into `buf` (premultiplied RGBA8, `len` bytes) if the scene changed.
 *
 * # Safety
 * `host` must be null or live; `buf` must be valid for `len` writable bytes.
 */
struct SbFrame sb_host_render(struct SbHost *host, uint8_t *buf, size_t len);

/**
 * Advances Slint timers and animations; call once per host frame tick.
 */
void sb_tick(void);

/**
 * Pointer moved, in logical points from the top-left corner.
 *
 * # Safety
 * `host` must be null or live.
 */
bool sb_host_pointer_moved(const struct SbHost *host, float x, float y);

/**
 * Pointer button pressed, in logical points.
 *
 * # Safety
 * `host` must be null or live.
 */
bool sb_host_pointer_pressed(const struct SbHost *host, float x, float y, SbPointerButton button);

/**
 * Pointer button released, in logical points.
 *
 * # Safety
 * `host` must be null or live.
 */
bool sb_host_pointer_released(const struct SbHost *host, float x, float y, SbPointerButton button);

/**
 * Pointer left the view.
 *
 * # Safety
 * `host` must be null or live.
 */
bool sb_host_pointer_exited(const struct SbHost *host);

/**
 * Scroll delta at `x`,`y`, all in logical points.
 *
 * # Safety
 * `host` must be null or live.
 */
bool sb_host_pointer_scrolled(const struct SbHost *host, float x, float y, float dx, float dy);

/**
 * The host view gained (true) or lost (false) keyboard focus.
 *
 * # Safety
 * `host` must be null or live.
 */
bool sb_host_focus_changed(const struct SbHost *host, bool focused);

/**
 * A key went down; `text` is UTF-8 (the typed character or a Slint key code).
 *
 * Returns true when Slint accepted the key. Returns false when the scene
 * rejected it or the call failed. A rejection leaves `sb_last_error` null, so
 * the host can move focus (Tab with no next item). A failure sets it.
 *
 * # Safety
 * `host` must be null or live; `text` null or NUL-terminated.
 */
bool sb_host_key_pressed(const struct SbHost *host, const char *text);

/**
 * A key went up. Returns false only when the call failed; see `sb_last_error`.
 * A release the scene ignores is still a success.
 *
 * # Safety
 * `host` must be null or live; `text` null or NUL-terminated.
 */
bool sb_host_key_released(const struct SbHost *host, const char *text);

/**
 * Replaces the input-method preedit. `utf16_start`/`utf16_end` select inside
 * `preedit` in UTF-16 code units (an AppKit `NSRange`). A negative start means
 * no selection. An empty `preedit` clears the composition.
 *
 * Returns false on failure; see `sb_last_error`.
 *
 * # Safety
 * `host` must be null or live; `preedit` null or NUL-terminated.
 */
bool sb_host_composition_update(const struct SbHost *host,
                                const char *preedit,
                                int32_t utf16_start,
                                int32_t utf16_end);

/**
 * Inserts `text` and clears the preedit. Empty `text` only clears it.
 *
 * Returns false on failure; see `sb_last_error`.
 *
 * # Safety
 * `host` must be null or live; `text` null or NUL-terminated.
 */
bool sb_host_composition_commit(const struct SbHost *host, const char *text);

/**
 * Writes the Slint key text for one AppKit key event into `out`.
 *
 * Returns true when a key was written. Returns false when the event is not a
 * Slint key (the buffer is then an empty string and `sb_last_error` is null)
 * or the call failed (`sb_last_error` is set).
 *
 * # Safety
 * `characters` and `ignoring` must be null or NUL-terminated. `out` must be
 * null or valid for `out_len` writable bytes.
 */
bool sb_appkit_key_text(uint16_t key_code,
                        const char *characters,
                        const char *ignoring,
                        uint32_t modifiers,
                        char *out,
                        size_t out_len);

/**
 * Sets the demo form's `name` property.
 *
 * # Safety
 * `host` must be null or live; `name` null or NUL-terminated.
 */
void sb_demo_set_name(const struct SbHost *host, const char *name);

/**
 * Registers `callback` for the demo form's `submitted(name)`; null clears it.
 * `user_data` is passed back untouched and must outlive the host.
 *
 * # Safety
 * `host` must be null or live.
 */
void sb_demo_on_submitted(const struct SbHost *host, SbSubmittedFn callback, void *user_data);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SLINT_BINDINGS_H */
